// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// wsCreate
SEXP wsCreate(std::string url);
RcppExport SEXP _websocketClient_wsCreate(SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(wsCreate(url));
    return rcpp_result_gen;
END_RCPP
}
// wsSend
void wsSend(SEXP ws_xptr, std::string msg);
RcppExport SEXP _websocketClient_wsSend(SEXP ws_xptrSEXP, SEXP msgSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ws_xptr(ws_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type msg(msgSEXP);
    wsSend(ws_xptr, msg);
    return R_NilValue;
END_RCPP
}
// wsPoll
void wsPoll(SEXP ws_xptr);
RcppExport SEXP _websocketClient_wsPoll(SEXP ws_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ws_xptr(ws_xptrSEXP);
    wsPoll(ws_xptr);
    return R_NilValue;
END_RCPP
}
// wsClose
void wsClose(SEXP ws_xptr);
RcppExport SEXP _websocketClient_wsClose(SEXP ws_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ws_xptr(ws_xptrSEXP);
    wsClose(ws_xptr);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_websocketClient_wsCreate", (DL_FUNC) &_websocketClient_wsCreate, 1},
    {"_websocketClient_wsSend", (DL_FUNC) &_websocketClient_wsSend, 2},
    {"_websocketClient_wsPoll", (DL_FUNC) &_websocketClient_wsPoll, 1},
    {"_websocketClient_wsClose", (DL_FUNC) &_websocketClient_wsClose, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_websocketClient(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
