# Generated by cpp11: do not edit by hand

wsCreate <- function(uri, loop_id, robjPublic, robjPrivate, accessLogChannels, errorLogChannels, maxMessageSize) {
  .Call("_websocket_wsCreate", uri, loop_id, robjPublic, robjPrivate, accessLogChannels, errorLogChannels, maxMessageSize, PACKAGE = "websocket")
}

wsAppendHeader <- function(wsc_xptr, key, value) {
  invisible(.Call("_websocket_wsAppendHeader", wsc_xptr, key, value, PACKAGE = "websocket"))
}

wsAddProtocols <- function(wsc_xptr, protocols) {
  invisible(.Call("_websocket_wsAddProtocols", wsc_xptr, protocols, PACKAGE = "websocket"))
}

wsConnect <- function(wsc_xptr) {
  invisible(.Call("_websocket_wsConnect", wsc_xptr, PACKAGE = "websocket"))
}

wsSend <- function(wsc_xptr, msg) {
  invisible(.Call("_websocket_wsSend", wsc_xptr, msg, PACKAGE = "websocket"))
}

wsClose <- function(wsc_xptr, code, reason) {
  invisible(.Call("_websocket_wsClose", wsc_xptr, code, reason, PACKAGE = "websocket"))
}

wsProtocol <- function(wsc_xptr) {
  .Call("_websocket_wsProtocol", wsc_xptr, PACKAGE = "websocket")
}

wsState <- function(wsc_xptr) {
  .Call("_websocket_wsState", wsc_xptr, PACKAGE = "websocket")
}

wsUpdateLogChannels <- function(wsc_xptr, accessOrError, setOrClear, logChannels) {
  invisible(.Call("_websocket_wsUpdateLogChannels", wsc_xptr, accessOrError, setOrClear, logChannels, PACKAGE = "websocket"))
}
