# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wsCreate <- function(uri, robjPublic, robjPrivate, accessLogChannels, errorLogChannels) {
    .Call(`_websocket_wsCreate`, uri, robjPublic, robjPrivate, accessLogChannels, errorLogChannels)
}

wsAppendHeader <- function(client_xptr, key, value) {
    invisible(.Call(`_websocket_wsAppendHeader`, client_xptr, key, value))
}

wsAddProtocols <- function(client_xptr, protocols) {
    invisible(.Call(`_websocket_wsAddProtocols`, client_xptr, protocols))
}

wsConnect <- function(client_xptr) {
    invisible(.Call(`_websocket_wsConnect`, client_xptr))
}

wsRestart <- function(client_xptr) {
    invisible(.Call(`_websocket_wsRestart`, client_xptr))
}

wsPoll <- function(client_xptr) {
    invisible(.Call(`_websocket_wsPoll`, client_xptr))
}

wsRun <- function(client_xptr) {
    invisible(.Call(`_websocket_wsRun`, client_xptr))
}

wsSend <- function(client_xptr, msg) {
    invisible(.Call(`_websocket_wsSend`, client_xptr, msg))
}

wsReset <- function(client_xptr) {
    invisible(.Call(`_websocket_wsReset`, client_xptr))
}

wsClose <- function(client_xptr, code, reason) {
    invisible(.Call(`_websocket_wsClose`, client_xptr, code, reason))
}

wsStopped <- function(client_xptr) {
    .Call(`_websocket_wsStopped`, client_xptr)
}

wsProtocol <- function(client_xptr) {
    .Call(`_websocket_wsProtocol`, client_xptr)
}

wsState <- function(client_xptr) {
    .Call(`_websocket_wsState`, client_xptr)
}

wsUpdateLogChannels <- function(client_xptr, accessOrError, setOrClear, logChannels) {
    invisible(.Call(`_websocket_wsUpdateLogChannels`, client_xptr, accessOrError, setOrClear, logChannels))
}

