# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wsCreate <- function(url) {
    .Call(`_websocketClient_wsCreate`, url)
}

wsSend <- function(ws_xptr, msg) {
    invisible(.Call(`_websocketClient_wsSend`, ws_xptr, msg))
}

wsReceive <- function(ws_xptr, onMessage) {
    invisible(.Call(`_websocketClient_wsReceive`, ws_xptr, onMessage))
}

wsClose <- function(ws_xptr) {
    invisible(.Call(`_websocketClient_wsClose`, ws_xptr))
}

wsState <- function(ws_xptr) {
    .Call(`_websocketClient_wsState`, ws_xptr)
}

wssCreate <- function(uri, onMessage, onClose) {
    .Call(`_websocketClient_wssCreate`, uri, onMessage, onClose)
}

wssConnect <- function(client_xptr) {
    invisible(.Call(`_websocketClient_wssConnect`, client_xptr))
}

wssPoll <- function(client_xptr) {
    invisible(.Call(`_websocketClient_wssPoll`, client_xptr))
}

wssSend <- function(client_xptr, msg) {
    invisible(.Call(`_websocketClient_wssSend`, client_xptr, msg))
}

